# Generated by Django 4.2 on 2025-11-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название сериала"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор для URL",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug сериала",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание сериала"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="series/",
                        verbose_name="Обложка сериала",
                    ),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год выхода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сериал",
                "verbose_name_plural": "Сериалы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(verbose_name="Номер сезона"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Название сезона",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание сезона"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seasons/",
                        verbose_name="Обложка сезона",
                    ),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год выхода"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="series.series",
                        verbose_name="Сериал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сезон",
                "verbose_name_plural": "Сезоны",
                "ordering": ["series", "number"],
                "unique_together": {("series", "number")},
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название серии"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, verbose_name="Slug серии"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="episodes/",
                        verbose_name="Обложка сезона",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        verbose_name="Номер серии в сезоне"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание серии"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="series.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Серия",
                "verbose_name_plural": "Серии",
                "ordering": ["season", "number"],
                "unique_together": {("season", "slug")},
            },
        ),
    ]
